### ISSUE TITLE
give field of view as input instead of number of points

### ISSUE THREAD

**Issue by fcaprile** [andreabassi78/napari-psf-simulator#10]
The number of points for the calculation is processed internally as a big number so that the resolution of the system is big enough (resulting in a bigger fiend of view being calculated). The resulting field is then cropped so that the requested field of view is shown.

**Comment by fcaprile** [comment]
added a function to calculate the number of divisions to show given the field of view and added the dimensions of the field to show as parameters for the psf simulator, which crops the resulting psf

**Comment by andreabassi78** [comment]
After these changes, the `Plot PSF profile in Console` gives the error `x and y must have the same first dimension, but...` in Scalar Propagation mode.

**Comment by fcaprile** [comment]
Fixed by also cropping the variables used for showing the field on console
