### ISSUE TITLE
running error for python<3.10

### ISSUE THREAD

**Issue by andreabassi78** [andreabassi78/napari-psf-simulator#11]
The current syntax used in Pyfocus required python >=3.10. See for example:
https://github.com/fcaprile/PyFocus/blob/8d885383787d8225130cf05473de789fda697ca0/src/model/focus_field_calculators/base.py#L21C6-L21C67

I suggest changing the syntax back to make sure the code works for previous versions.
Otherwise, we have to set some requirements for the plugin, but we might lose some users.

**Comment by fcaprile** [comment]
Changed type hints to be compatible with python<3.10

**Comment by andreabassi78** [comment]
Hi @fcaprile, I'm afraid the notation should be changes here too.
https://github.com/fcaprile/PyFocus/blob/8d885383787d8225130cf05473de789fda697ca0/src/model/focus_field_calculators/base.py#L68

Sorry, I would change it myself but I'm not familiar with this notation yet.

**Comment by fcaprile** [comment]
Thanks @andreabassi78, modified the typing notation there as well.
