### ISSUE TITLE
z axis scaling used not when rotating stack view

### ISSUE THREAD

**Issue by micropolimi** [andreabassi78/napari-psf-simulator#2]
The voxels have the same x,y,z size even when the values for dxy and dz are not the same. You can see this by changing the order of the visible axis (reslicing)

**Comment by andreabassi78** [comment]
This looks like a very bad visualization thing. Should be able to solve it by changing the scale of the layers, but then I should release a new version

**Comment by andreabassi78** [comment]
Solved, [using a scale](https://github.com/andreabassi78/napari-psf-simulator/blob/6b22e90bb22fee94b4e130e5e55e85dc337a7a47/src/napari_psf_simulator/_widget.py#L162-L167), and new version released 0.1.4. 
Strangely, when [centering the stack in the central frame](https://github.com/andreabassi78/napari-psf-simulator/blob/6b22e90bb22fee94b4e130e5e55e85dc337a7a47/src/napari_psf_simulator/_widget.py#L198) I had inconsistent visualization. So I added [this line](https://github.com/andreabassi78/napari-psf-simulator/blob/6b22e90bb22fee94b4e130e5e55e85dc337a7a47/src/napari_psf_simulator/_widget.py#L183). Seems a reasonable fix and I haven't experienced any issue.
