### ISSUE TITLE
Combination of multiple aberrations

### ISSUE THREAD

**Issue by LREIN663** [andreabassi78/napari-psf-simulator#5]
Is there the option to combine multiple aberrations at the same time? 
It would be awesome to see the combined effects.

**Comment by andreabassi78** [comment]
Hi @LREIN663, sorry for taking so long to respond.
We are currently making major changes to the simulator (including vectorial propagation). We are also thinking to combine multiple aberrations but it is not our first priority. However, I made [a script that combines two aberrations](https://github.com/andreabassi78/napari-psf-simulator/blob/main/src/_widget_runner_with_multiple%20aberrations.py) to show how to do that. This is not going to be included in the plugin yet and unfortunately, you should download or forge the project to run it.

**Comment by LREIN663** [comment]
Thanks alot for your response and the script! 
I'm very excited to see the simulations after the update. For now I will close the this issue and check out the script as soon as I have time. 
Greetings,
Lenny
